services:
  - type: web
    name: django-forum
    env: python
    buildCommand: 
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn forum.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: django-forum-db
          property: connectionString

databases:
  - name: django-forum-db
