# Generated by Django 5.2.1 on 2025-05-25 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0003_articles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
